# generated by ChatGPT :p

FROM golang:alpine

RUN apk add build-base

WORKDIR /app

COPY . .

RUN go build -o go-lsi .

EXPOSE 8080

ENV PORT=8080
ENV DB=./path/to/db
ENV SIGNIGN_KEY=log-string-to-sign-jwt-tokens
ENV LINNWORKS_APP_ID=linny-app-id
ENV LINNWORKS_APP_SECRET=linny-app-secret
ENV LINNWORKS_APP_TOKEN=linny-app-token
ENV SQUARE_ACCESS_TOKEN=square-access-token
ENV SQUARE_HOST=square-host
ENV SQUARE_API_VERSION=2023-01-19
ENV SQUARE_LOCATION_ID=square-location-id
ENV SQUARE_TEAM_MEMBER_IDS=id1,id2,id3

CMD ["./go-lsi"]
