# generated by ChatGPT :p

IMAGE_NAME=go-lsi:latest

build:
	docker build -t $(IMAGE_NAME) .

run:
	docker run --env-file .env -p 8080:8080  go-lsi:latest

test:
	go test ./...

format:
	go fmt ./...

.PHONY: build run test format
